apiVersion: apps/v1
kind: Deployment
metadata:
  name: hoobank-deployment
  labels:
    app: hoobank
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hoobank
  template:
    metadata:
      labels:
        app: hoobank
    spec:
      containers:
      - name: hoobank
        image: imgkuber1:latest
        ports:
        - containerPort: 5173
