apiVersion: v1
kind: Service
metadata:
  name: hoobank-service
spec:
  selector:
    app: hoobank
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
      nodePort: 30010
  type: NodePort
